version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: orbital_edge_imaging
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: db
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: 1234
      TYPEORM_DATABASE: orbital_edge_imaging
      TYPEORM_SYNCHRONIZE: "true"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orbital_edge_imaging"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: orbital_edge_imaging
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: